### ISSUE TITLE
Fix .serve() methods in examples

### ISSUE THREAD

**Issue by DanisJa** [denoland/denobyexample#116]
Deno.serve is not a function for some examples, I suppose that way is redundant, so just change it to import and use only `serve()` method, could someone please fix that? Thanks.

**Comment by iuioiua** [comment]
`Deno.serve()` is available on the latest version of Deno and has been for some time. `serve()` from the Standard Library is now deprecated in favour of `Deno.serve()` too.

It'd also be good to provide some examples and references.

**Comment by DanisJa** [comment]
@iuioiua When using examples from https://examples.deno.land/ - and running `deno run --allow-net https://examples.deno.land/http-server-websocket.ts` sometimes causes errors saying `Deno.serve() is not a function` for some reason. 

After testing again now, it worked.

I apologize for the confusion. Closing the issue.
