### ISSUE TITLE
Replace makefile with deno.jsonc

### ISSUE THREAD

**Issue by thegaryroberts** [denoland/denobyexample#22]
Makefiles are so last week (also it would act as an additional example of how to use the new task runner).

**Comment by littledivy** [comment]
> Makefiles are so last week

nope, not sure why you say that.

> it would act as an additional example of how to use the new task runner

yeah, good point and we should do `deno task` for this reason.

**Comment by thegaryroberts** [comment]
@littledivy 

> Makefiles are so last week
> nope, not sure why you say that.

It was both a light-hearted joke and a celebration of Deno tasks which had been introduced in the previous week. Thanks for resolving this!
