### ISSUE TITLE
Add copy button to code snippets

### ISSUE THREAD

**Issue by mrkldshv** [denoland/denobyexample#27]
Currently, it's not easy to copy code snippet from the example. When I'm trying to copy code by selecting it with mouse, this copies both the description and the code snippet. I think it would be great to add copy button to the code snippets. As alternative solution, we can adjust layout to make copying code using mouse easier.

**Comment by LeoDog896** [comment]
Does anyone have any ideas about where to place the copy to clipboard button per code block?

**Comment by lino-levan** [comment]
@LeoDog896 this would probably be done here https://github.com/denoland/denobyexample/blob/2240ce9c16a0b09a8a1e87994cbaeedfd1c7d754/www/routes/%5Bid%5D.tsx#L223

**Comment by LeoDog896** [comment]
Sorry about the bad wording -- more of a design question, but that helps too!

**Comment by lino-levan** [comment]
Ah okay, that makes more sense. I would place it in the top right of the box because that seems to be the standard. 

See: https://vitejs.dev/guide/

**Comment by lino-levan** [comment]
I think this requires some design work. @hashrock (sorry for the ping), are you aware of a deno-style copy svg? I wasn't able to find any official deno projects with a copy button.

**Comment by hashrock** [comment]
I think we can use this svg:

https://github.com/denoland/doc_components/blob/main/icons.tsx#L91

![image](https://user-images.githubusercontent.com/3132889/213908505-fca5e417-f318-4462-9534-a71a98c0ef8f.png)
