### ISSUE TITLE
[Meta] What's the main reason for seperating this from the manual's examples?

### ISSUE THREAD

**Issue by LeoDog896** [denoland/denobyexample#45]
The manual has a [similar list of examples](https://deno.land/manual@v1.29.2/examples/), including longer ones such as a [chat app](https://deno.land/manual@v1.29.2/examples/chat_app). Given this, why have both?

**Comment by lino-levan** [comment]
I think both have some value, and this is simply for separation of concerns. The manual has a more focused set of examples designed for a beginner to learn how to use Deno. Longer examples are useful for that goal. Deno by example (aspires to) have short examples on how to do basically every common operation in Deno. In my eyes, they have fundamentally different purposes and should stay separated.

If I were to be responsible for choosing one of the two to cut (which I would not advocate for), I would borderline cut the examples from the manual.

**Comment by LeoDog896** [comment]
Alright, that makes more sense! Thanks for clarifying -- I'll leave this issue as completed, and if anyone else has an issue with it, let me know and I'll reopen it.
