### ISSUE TITLE
`deno run` command in the example page doesn't work if there are 2 or more code blocks in that page

### ISSUE THREAD

**Issue by kt3k** [denoland/denobyexample#49]
Some examples (eg. web worker) need more than 1 code block to describe the example, but currently that's not handled.

https://github.com/denoland/denobyexample/blob/898d1ebcab9a30f2a012c6fa5c782580c486492e/www/routes/%5Bid%5D.tsx#L21

**Comment by lino-levan** [comment]
I will look into this. Looks like the page itself should probably serve up `main.ts` in the case of multiple files. We'd also need to handle the other files that may or may not show up.

**Comment by kt3k** [comment]
> Looks like the page itself should probably serve up main.ts in the case of multiple files.

Or maybe we can handle `/[id]/main.ts` path for it?
