### ISSUE TITLE
Websocket example doesn't appear to do anything

### ISSUE THREAD

**Issue by dannyfritz** [denoland/denobyexample#94]
## Observed:
```
$ deno run --allow-net https://examples.deno.land/websocket.ts
$
```
(no output)

## Expected:
Logging about the socket readyState and a "ping" event echoed back.

**Comment by lino-levan** [comment]
This is expected behavior. `ws://ws.example.com` doesn't point to a real WS server. Ideally we'd integrate with https://examples.deno.land/http-server-websocket. I'll pick this up tomorrow probably.
